#!/usr/bin/python
from os import listdir
from os.path import isfile, join
import os.path
#import os
import sys
import time
#import socket

#serversocket = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
#serversocket.bind(('192.168.56.102', 3001))
#serversocket.listen(5)

def WriteDebugFile(level,exstring):
	debugpath = "/home/deneme1"
	directory = "/debug"
	if not os.path.exists(debugpath + directory):
		os.makedirs(debugpath + directory)
	timestr = time.strftime("%Y%m%d-%H%M%S")
	fdebug = open(debugpath + directory + "/" + "LIST" + "-" +  level + "-" + timestr, "w+")
	fdebug.write(exstring)
	fdebug.close()	

try:
	buf = sys.stdin.readline().strip()
	if len(buf):
		list = [f for f in listdir("/home/deneme1/Desktop/py_app_files") if isfile(join("/home/deneme1/Desktop/py_app_files",f))]
		print list
		sys.stdout.flush()
		WriteDebugFile("20", ": File list successfully sent!")

except Exception as ex:
	WriteDebugFile("40",str(ex))

